# -*- coding: utf-8 -*-
"""2.add-charts.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8xFzboExhrLbXZW8JkE0ggVORGcxbMv
"""

from openpyxl import load_workbook
from openpyxl.chart import BarChart, Reference

wb = load_workbook('/content/pivot_table.xlsx')

sheet = wb['Report']

min_column = wb.active.min_column
min_row = wb.active.min_row
max_row = wb.active.max_row
max_column = wb.active.max_column

barchart = BarChart()

data = Reference(sheet,
          min_col=min_column+1,
          max_col=max_column,
          min_row=min_row,
          max_row=max_row)

categories = Reference(sheet,
          min_col=min_column,
          max_col=min_column,
          min_row=min_row+1,
          max_row=max_row)

barchart.add_data(data, titles_from_data=True)
barchart.set_categories(categories)

sheet.add_chart(barchart, "B12")

barchart.title = "Sales by Product line"
barchart.y_axis.title = "Sales"
barchart.x_axis.title = "Product line"
barchart.style = 5

wb.save('barchart.xlsx')